
# Aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias aplay_tts='aplay -r 22050 -c 1 -f S16_LE -t raw'
alias cat='bat -p --italic-text=always'
alias chx='chmod +x'
alias config='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias cp='cp -rvn'
alias du='du -sh'
alias e='eza --icons=always --color=always'
alias ee='eza --icons=always --color=always -A'
alias eip='echo $(curl -s http://ifconfig.me)'
alias fix-perms-dirs='find /home/sweet/bin -type d -exec chmod 774 {} +'
alias fix-perms-files='find /home/sweet/bin -type f -exec chmod 664 {} +'
alias gb='go build'
alias gcl='git clone'
alias gmi='go mod init'
alias gmt='go mod tidy'
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias hx='nvim'
alias ll='eza --icons=always -lah'
alias l='eza --icons=always -a1'
alias ls='eza --icons=always'
alias lsblk='lsblk -e7'

alias mpvs='mpv --vo=kitty --vo-kitty-use-shm=yes ytdl://ytsearch:'
alias mpvv='mpv --vo=kitty --vo-kitty-use-shm=yes'

alias mv='mv -i'
alias nv='nvim'

alias pm='podman'
alias py='python'

alias rsync-copy='rsync -avz --progress -h'
alias rsync-move='rsync -avz --progress -h --remove-source-files'
alias rsync-synchronize='rsync -avzu --delete --progress -h'
alias rsync-update='rsync -avzu --progress -h'

alias top='btop'
alias tree='eza -a -I .git --tree'
alias tsm='transmission-remote'
alias wget-pdf='wget -r -l 1 -nH -nd -np --ignore-case -A '\''*.pdf'\'''
alias ydl='yt-dlp'
alias yta='yt-dlp --embed-thumbnail --embed-metadata -x'
alias ytd='yt-dlp --embed-thumbnail --embed-metadata'
alias zrc='hx ~/.zshrc && source ~/.zshrc'

alias -g G='| grep'
